name: Flutter CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart format --set-exit-if-changed .

  # tests:
  #   name: Run unit tests
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       sdk: [ stable, beta, 2.12.1 ]
  #       platform: [ vm, chrome ]
  #   defaults:
  #     run:
  #       working-directory: lib
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: dart-lang/setup-dart@v1
  #       with:
  #         sdk: ${{ matrix.sdk }}
  #     - run: pub get
  #     - run: dart test --chain-stack-traces --platform=${{ matrix.platform }}

  publish-dry-run:
    name: Publish dry-run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: k-paxian/dart-package-publisher@master
        with:
          dryRunOnly: true
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}